/**
 * Dizionario italiano legal — informativa privacy, termini di servizio e
 * pagina disclaimer.
 *
 * NOTA: solo `seo`, `updatedTemplate` e l'avviso di pagina (`notice`, testo
 * di interfaccia, non testo legale) sono tradotti. Il testo legale
 * (heading, intro, sections, outro) resta in inglese dalla sorgente, come
 * richiesto — i testi legali non si traducono in questo progetto.
 *
 * `updatedTemplate` prende un `{date}` formattato dalla pagina dal valore
 * last-updated della pagina stessa (le date NON si traducono, restano con la
 * sorgente della pagina). Il template dell'email di contatto \u00e8 riempito con
 * l'indirizzo di site-config (identificatore NON traducibile). Nomi di route
 * API e provider (`/api/ai/math`, DeepSeek) sono identificatori e restano
 * invariati.
 */

import type { LegalStrings } from '../types.js';

export const legal: LegalStrings = {
  notice: {
    title: 'Nota importante su questa pagina',
    body:
      'Il testo legale riportato di seguito \u00e8 la versione inglese autorevole. In caso di ' +
      'conflitto tra l\u2019interfaccia tradotta di questa pagina e il testo legale in inglese, ' +
      'prevale il testo inglese.',
  },
  privacy: {
    seo: {
      title: 'Informativa sulla privacy',
      description:
        'Informativa sulla privacy di Graphing Calculator: niente account, niente analisi, niente cookie. ' +
        'I tuoi messaggi all\u2019assistente AI vanno all\u2019endpoint server dell\u2019app.',
    },
    updatedTemplate: 'Ultimo aggiornamento: {date}',
    heading: 'Privacy Policy',
    intro: [
      'The Graphing Calculator is designed to work without collecting your personal data. ' +
        'This policy describes, in plain terms, what happens with your information.',
    ],
    sections: [
      {
        heading: 'What we collect',
        body: [
          'Nothing by default. There are no accounts, no sign-ups, and no analytics. Browsing ' +
            'the site, plotting functions, and saving graphs send no usage data, identifiers, or ' +
            'personal information to any server.',
        ],
      },
      {
        heading: 'AI assistant',
        body: [
          'When you send a message to the AI math assistant, your message and a compact ' +
            'summary of your current calculator state (expressions, viewport) are sent to the ' +
            'site\u2019s own server endpoint (/api/ai/math). If an AI provider key is configured, ' +
            'the server forwards your message to the AI provider (DeepSeek) to generate a ' +
            'response. The server never logs your messages or any API key; rate-limiting state ' +
            'is kept only in memory and expires within minutes.',
          'When no provider key is configured, the assistant runs in a clearly labeled ' +
            'mock mode: responses are generated by deterministic local logic and no AI provider ' +
            'is contacted. Local intents (for example, \u201cplot y = x^2\u201d) are handled ' +
            'entirely in your browser and never reach a server.',
        ],
      },
      {
        heading: 'Cookies',
        body: [
          'The site sets no cookies and uses no third-party trackers. Because there are no ' +
            'analytics and no advertising, there is no cookie banner and no consent to manage.',
        ],
      },
      {
        heading: 'What stays in your browser',
        body: [
          'Your theme preference and your calculator workspace (expressions, viewport, ' +
            'settings) are stored only in your own browser\u2019s localStorage. They never leave ' +
            'your device. Clearing your browser\u2019s site data removes them permanently.',
        ],
      },
      {
        heading: 'Contact',
        body: ['If you have questions about this policy, email {email}.'],
      },
    ],
    outro: [
      'This policy will be updated if the product\u2019s data practices change. The ' +
        'last-updated date above always reflects the current version.',
    ],
  },
  terms: {
    seo: {
      title: 'Termini di servizio',
      description: 'Termini di servizio di Graphing Calculator: regole di utilizzo e disclaimer.',
    },
    updatedTemplate: 'Ultimo aggiornamento: {date}',
    heading: 'Terms of Service',
    sections: [
      {
        heading: 'The service',
        body: [
          'The Graphing Calculator is provided as-is, for education and exploration. While we ' +
            'aim for correctness, we make no guarantees about the accuracy of any output, and the ' +
            'tool is not professional mathematical, engineering, or financial advice.',
        ],
      },
      {
        heading: 'Acceptable use',
        body: [
          'Use the calculator for lawful purposes only. Do not attempt to disrupt the service, ' +
            'probe it for vulnerabilities, or use it in a way that harms others.',
        ],
      },
      {
        heading: 'Changes',
        body: [
          'These terms may be updated as the product evolves; the last-updated date above ' +
            'reflects the current version. Continued use of the site after changes constitutes ' +
            'acceptance of the updated terms.',
        ],
      },
    ],
  },
  disclaimer: {
    seo: {
      title: 'Avvertenze legali',
      description:
        'Disclaimer di Graphing Calculator: le risposte AI e i risultati numerici sono ' +
        'informativi; verifica in modo indipendente i calcoli importanti.',
    },
    updatedTemplate: 'Ultimo aggiornamento: {date}',
    heading: 'Disclaimer',
    sections: [
      {
        heading: 'AI assistant output is informational',
        body: [
          'The built-in AI math assistant explains concepts and interprets requests in plain ' +
            'language, but it can make mistakes — including confidently stated ones. Treat AI ' +
            'answers as a starting point, not as authoritative mathematics.',
        ],
      },
      {
        heading: 'Numerical results are computed, not proven',
        body: [
          'Roots, derivatives, integrals, limits, and other analysis results are computed ' +
            'numerically with floating-point arithmetic. They are accurate to the displayed ' +
            'precision under normal conditions, but rounding and sampling can introduce small ' +
            'errors — especially near discontinuities, sharp corners, or asymptotes. For ' +
            'homework, exams, engineering, or any decision that matters, verify important ' +
            'calculations independently.',
        ],
      },
      {
        heading: 'No professional advice',
        body: [
          'Nothing on this site constitutes professional advice of any kind — mathematical, ' +
            'educational, financial, or otherwise. The content is provided for general ' +
            'educational purposes.',
        ],
      },
      {
        heading: 'Your graphs stay yours',
        body: [
          'Graphs you save are stored only in your own browser. Shared links encode the graph ' +
            'in the link itself, so anyone with the link can open it. Do not share links ' +
            'containing anything you would not want others to see.',
        ],
      },
    ],
    outro: [
      'By using this site you accept that its authors are not liable for decisions made on ' +
        'the basis of its output. See the Terms of Service for details.',
    ],
  },
};
