/**
 * Diccionario español de legal — páginas de política de privacidad, términos
 * de servicio y aviso legal.
 *
 * NOTA: por decisión explícita del encargo, solo se traducen el `seo`, la
 * plantilla de aviso de actualización (`updatedTemplate`) y el aviso de
 * página (`notice`, texto de interfaz, no legal). Los `heading`,
 * los cuerpos legales (`intro`, `sections`, `outro`) y todo el texto de las
 * páginas se conservan en inglés para no crear una versión legal vinculante
 * sin revisión jurídica.
 *
 * `updatedTemplate` recibe un `{date}` formateado por la página a partir de
 * su propio valor de última actualización (las fechas NO SE TRADUCEN, solo
 * las acompaña el texto). La plantilla del correo de contacto se rellena con
 * la dirección de configuración del sitio (identificador, NO SE TRADUCE).
 * La ruta de API (`/api/ai/math`) y los nombres de proveedores (DeepSeek)
 * son identificadores y se mantienen igual.
 */

export const legal = {
  notice: {
    title: 'Nota importante sobre esta página',
    body:
      'El texto legal que aparece a continuación es la versión inglesa autorizada. Si existe ' +
      'algún conflicto entre la interfaz traducida de esta página y el texto legal en inglés, ' +
      'prevalecerá el texto en inglés.',
  },
  privacy: {
    seo: {
      title: 'Política de privacidad',
      description:
        'Política de privacidad de Graphing Calculator: sin cuentas, sin analíticas, sin ' +
        'cookies. Tus mensajes al asistente de IA llegan al propio servidor de la aplicación.',
    },
    updatedTemplate: 'Última actualización: {date}',
    heading: 'Privacy Policy',
    intro: [
      'The Graphing Calculator is designed to work without collecting your personal data. ' +
        'This policy describes, in plain terms, what happens with your information.',
    ],
    sections: [
      {
        heading: 'What we collect',
        body: [
          'Nothing by default. There are no accounts, no sign-ups, and no analytics. Browsing ' +
            'the site, plotting functions, and saving graphs send no usage data, identifiers, or ' +
            'personal information to any server.',
        ],
      },
      {
        heading: 'AI assistant',
        body: [
          'When you send a message to the AI math assistant, your message and a compact ' +
            'summary of your current calculator state (expressions, viewport) are sent to the ' +
            'site\u2019s own server endpoint (/api/ai/math). If an AI provider key is configured, ' +
            'the server forwards your message to the AI provider (DeepSeek) to generate a ' +
            'response. The server never logs your messages or any API key; rate-limiting state ' +
            'is kept only in memory and expires within minutes.',
          'When no provider key is configured, the assistant runs in a clearly labeled ' +
            'mock mode: responses are generated by deterministic local logic and no AI provider ' +
            'is contacted. Local intents (for example, \u201cplot y = x^2\u201d) are handled ' +
            'entirely in your browser and never reach a server.',
        ],
      },
      {
        heading: 'Cookies',
        body: [
          'The site sets no cookies and uses no third-party trackers. Because there are no ' +
            'analytics and no advertising, there is no cookie banner and no consent to manage.',
        ],
      },
      {
        heading: 'What stays in your browser',
        body: [
          'Your theme preference and your calculator workspace (expressions, viewport, ' +
            'settings) are stored only in your own browser\u2019s localStorage. They never leave ' +
            'your device. Clearing your browser\u2019s site data removes them permanently.',
        ],
      },
      {
        heading: 'Contact',
        body: ['If you have questions about this policy, email {email}.'],
      },
    ],
    outro: [
      'This policy will be updated if the product\u2019s data practices change. The ' +
        'last-updated date above always reflects the current version.',
    ],
  },
  terms: {
    seo: {
      title: 'Términos de servicio',
      description: 'Términos de servicio de Graphing Calculator: reglas de uso y avisos legales.',
    },
    updatedTemplate: 'Última actualización: {date}',
    heading: 'Terms of Service',
    sections: [
      {
        heading: 'The service',
        body: [
          'The Graphing Calculator is provided as-is, for education and exploration. While we ' +
            'aim for correctness, we make no guarantees about the accuracy of any output, and the ' +
            'tool is not professional mathematical, engineering, or financial advice.',
        ],
      },
      {
        heading: 'Acceptable use',
        body: [
          'Use the calculator for lawful purposes only. Do not attempt to disrupt the service, ' +
            'probe it for vulnerabilities, or use it in a way that harms others.',
        ],
      },
      {
        heading: 'Changes',
        body: [
          'These terms may be updated as the product evolves; the last-updated date above ' +
            'reflects the current version. Continued use of the site after changes constitutes ' +
            'acceptance of the updated terms.',
        ],
      },
    ],
  },
  disclaimer: {
    seo: {
      title: 'Aviso legal',
      description:
        'Aviso legal de Graphing Calculator: las respuestas de la IA y los resultados ' +
        'numéricos son informativos; verifica por tu cuenta los cálculos importantes.',
    },
    updatedTemplate: 'Última actualización: {date}',
    heading: 'Disclaimer',
    sections: [
      {
        heading: 'AI assistant output is informational',
        body: [
          'The built-in AI math assistant explains concepts and interprets requests in plain ' +
            'language, but it can make mistakes — including confidently stated ones. Treat AI ' +
            'answers as a starting point, not as authoritative mathematics.',
        ],
      },
      {
        heading: 'Numerical results are computed, not proven',
        body: [
          'Roots, derivatives, integrals, limits, and other analysis results are computed ' +
            'numerically with floating-point arithmetic. They are accurate to the displayed ' +
            'precision under normal conditions, but rounding and sampling can introduce small ' +
            'errors — especially near discontinuities, sharp corners, or asymptotes. For ' +
            'homework, exams, engineering, or any decision that matters, verify important ' +
            'calculations independently.',
        ],
      },
      {
        heading: 'No professional advice',
        body: [
          'Nothing on this site constitutes professional advice of any kind — mathematical, ' +
            'educational, financial, or otherwise. The content is provided for general ' +
            'educational purposes.',
        ],
      },
      {
        heading: 'Your graphs stay yours',
        body: [
          'Graphs you save are stored only in your own browser. Shared links encode the graph ' +
            'in the link itself, so anyone with the link can open it. Do not share links ' +
            'containing anything you would not want others to see.',
        ],
      },
    ],
    outro: [
      'By using this site you accept that its authors are not liable for decisions made on ' +
        'the basis of its output. See the Terms of Service for details.',
    ],
  },
};
