/**
 * Deutsche Legal-Wörterliste — Datenschutzerklärung, Nutzungsbedingungen und
 * Haftungsausschluss.
 *
 * Übersetzt sind nur der Hinweis (`updatedTemplate`), die SEO-Felder, die
 * Überschriften, der Seiten-Hinweis (`notice`, Oberflächentext, kein
 * Rechtstext) sowie Intro/Outro. Die rechtlichen Fließtexte (`body`)
 * bleiben bewusst auf Englisch — Rechtstexte werden nicht in einer
 * Übersetzung bereitgestellt.
 *
 * `updatedTemplate` erhält ein `{date}`, das die Seite aus ihrem eigenen
 * Aktualisierungsdatum formatiert (DO-NOT-TRANSLATE-Daten bleiben bei der
 * Seitenquelle). Die Kontakt-E-Mail-Vorlage wird mit der Site-Config-Adresse
 * gefüllt (DO-NOT-TRANSLATE-Identifikator). API-Route und Anbieternamen
 * (`/api/ai/math`, DeepSeek) sind Identifikatoren und bleiben unverändert.
 */

import type { LegalStrings } from '../types.js';

export const legal: LegalStrings = {
  notice: {
    title: 'Wichtiger Hinweis zu dieser Seite',
    body:
      'Der nachstehende Rechtstext ist die maßgebliche englische Fassung. Bei Widersprüchen ' +
      'zwischen der übersetzten Oberfläche dieser Seite und dem englischen Rechtstext ist der ' +
      'englische Text maßgeblich.',
  },
  privacy: {
    seo: {
      title: 'Datenschutzerklärung',
      description:
        'Datenschutzerklärung des Graphing Calculator: keine Konten, keine Analysen, keine Cookies. ' +
        'Ihre KI-Assistenten-Nachrichten gehen an den eigenen Server-Endpunkt der App.',
    },
    updatedTemplate: 'Zuletzt aktualisiert: {date}',
    heading: 'Datenschutzerklärung',
    intro: [
      'Der Graphing Calculator ist so konzipiert, dass er ohne Erhebung Ihrer persönlichen Daten ' +
        'funktioniert. Diese Richtlinie beschreibt in einfachen Worten, was mit Ihren Informationen geschieht.',
    ],
    sections: [
      {
        heading: 'What we collect',
        body: [
          'Nothing by default. There are no accounts, no sign-ups, and no analytics. Browsing ' +
            'the site, plotting functions, and saving graphs send no usage data, identifiers, or ' +
            'personal information to any server.',
        ],
      },
      {
        heading: 'AI assistant',
        body: [
          'When you send a message to the AI math assistant, your message and a compact ' +
            'summary of your current calculator state (expressions, viewport) are sent to the ' +
            'site\u2019s own server endpoint (/api/ai/math). If an AI provider key is configured, ' +
            'the server forwards your message to the AI provider (DeepSeek) to generate a ' +
            'response. The server never logs your messages or any API key; rate-limiting state ' +
            'is kept only in memory and expires within minutes.',
          'When no provider key is configured, the assistant runs in a clearly labeled ' +
            'mock mode: responses are generated by deterministic local logic and no AI provider ' +
            'is contacted. Local intents (for example, \u201cplot y = x^2\u201d) are handled ' +
            'entirely in your browser and never reach a server.',
        ],
      },
      {
        heading: 'Cookies',
        body: [
          'The site sets no cookies and uses no third-party trackers. Because there are no ' +
            'analytics and no advertising, there is no cookie banner and no consent to manage.',
        ],
      },
      {
        heading: 'What stays in your browser',
        body: [
          'Your theme preference and your calculator workspace (expressions, viewport, ' +
            'settings) are stored only in your own browser\u2019s localStorage. They never leave ' +
            'your device. Clearing your browser\u2019s site data removes them permanently.',
        ],
      },
      {
        heading: 'Contact',
        body: ['If you have questions about this policy, email {email}.'],
      },
    ],
    outro: [
      'Diese Richtlinie wird aktualisiert, wenn sich die Datenpraktiken des Produkts ändern. Das ' +
        'Aktualisierungsdatum oben spiegelt immer die aktuelle Version wider.',
    ],
  },
  terms: {
    seo: {
      title: 'Nutzungsbedingungen',
      description:
        'Nutzungsbedingungen des Graphing Calculator: Nutzungsregeln und Haftungsausschlüsse.',
    },
    updatedTemplate: 'Zuletzt aktualisiert: {date}',
    heading: 'Nutzungsbedingungen',
    sections: [
      {
        heading: 'The service',
        body: [
          'The Graphing Calculator is provided as-is, for education and exploration. While we ' +
            'aim for correctness, we make no guarantees about the accuracy of any output, and the ' +
            'tool is not professional mathematical, engineering, or financial advice.',
        ],
      },
      {
        heading: 'Acceptable use',
        body: [
          'Use the calculator for lawful purposes only. Do not attempt to disrupt the service, ' +
            'probe it for vulnerabilities, or use it in a way that harms others.',
        ],
      },
      {
        heading: 'Changes',
        body: [
          'These terms may be updated as the product evolves; the last-updated date above ' +
            'reflects the current version. Continued use of the site after changes constitutes ' +
            'acceptance of the updated terms.',
        ],
      },
    ],
  },
  disclaimer: {
    seo: {
      title: 'Haftungsausschluss',
      description:
        'Haftungsausschluss des Graphing Calculator: KI-Antworten und numerische Ergebnisse sind ' +
        'informativ; wichtige Berechnungen unabhängig verifizieren.',
    },
    updatedTemplate: 'Zuletzt aktualisiert: {date}',
    heading: 'Haftungsausschluss',
    sections: [
      {
        heading: 'AI assistant output is informational',
        body: [
          'The built-in AI math assistant explains concepts and interprets requests in plain ' +
            'language, but it can make mistakes — including confidently stated ones. Treat AI ' +
            'answers as a starting point, not as authoritative mathematics.',
        ],
      },
      {
        heading: 'Numerical results are computed, not proven',
        body: [
          'Roots, derivatives, integrals, limits, and other analysis results are computed ' +
            'numerically with floating-point arithmetic. They are accurate to the displayed ' +
            'precision under normal conditions, but rounding and sampling can introduce small ' +
            'errors — especially near discontinuities, sharp corners, or asymptotes. For ' +
            'homework, exams, engineering, or any decision that matters, verify important ' +
            'calculations independently.',
        ],
      },
      {
        heading: 'No professional advice',
        body: [
          'Nothing on this site constitutes professional advice of any kind — mathematical, ' +
            'educational, financial, or otherwise. The content is provided for general ' +
            'educational purposes.',
        ],
      },
      {
        heading: 'Your graphs stay yours',
        body: [
          'Graphs you save are stored only in your own browser. Shared links encode the graph ' +
            'in the link itself, so anyone with the link can open it. Do not share links ' +
            'containing anything you would not want others to see.',
        ],
      },
    ],
    outro: [
      'Durch die Nutzung dieser Seite akzeptieren Sie, dass ihre Autoren nicht für Entscheidungen ' +
        'haften, die auf Grundlage ihrer Ausgaben getroffen werden. Details finden Sie in den Nutzungsbedingungen.',
    ],
  },
};
