/**
 * English legal dictionary — privacy policy, terms of service, and
 * disclaimer pages.
 *
 * `updatedTemplate` takes a `{date}` formatted by the page from the page's
 * own last-updated value (DO-NOT-TRANSLATE dates stay with the page source).
 * The contact email template is filled with the site-config address
 * (DO-NOT-TRANSLATE identifier). API route and provider names (`/api/ai/math`,
 * DeepSeek) are identifiers and stay as-is.
 */

import type { LegalStrings } from '../types.js';

export const legal: LegalStrings = {
  notice: {
    title: 'Important note about this page',
    body:
      'The legal text below is the authoritative English version. If there is any conflict ' +
      "between this page's translated interface and the English legal text, the English " +
      'text controls.',
  },
  privacy: {
    seo: {
      title: 'Privacy Policy',
      description:
        'Privacy policy for the Graphing Calculator: no accounts, no analytics, no cookies. ' +
        'Your AI assistant messages go to the app\u2019s own server endpoint.',
    },
    updatedTemplate: 'Last updated: {date}',
    heading: 'Privacy Policy',
    intro: [
      'The Graphing Calculator is designed to work without collecting your personal data. ' +
        'This policy describes, in plain terms, what happens with your information.',
    ],
    sections: [
      {
        heading: 'What we collect',
        body: [
          'Nothing by default. There are no accounts, no sign-ups, and no analytics. Browsing ' +
            'the site, plotting functions, and saving graphs send no usage data, identifiers, or ' +
            'personal information to any server.',
        ],
      },
      {
        heading: 'AI assistant',
        body: [
          'When you send a message to the AI math assistant, your message and a compact ' +
            'summary of your current calculator state (expressions, viewport) are sent to the ' +
            'site\u2019s own server endpoint (/api/ai/math). If an AI provider key is configured, ' +
            'the server forwards your message to the AI provider (DeepSeek) to generate a ' +
            'response. The server never logs your messages or any API key; rate-limiting state ' +
            'is kept only in memory and expires within minutes.',
          'When no provider key is configured, the assistant runs in a clearly labeled ' +
            'mock mode: responses are generated by deterministic local logic and no AI provider ' +
            'is contacted. Local intents (for example, \u201cplot y = x^2\u201d) are handled ' +
            'entirely in your browser and never reach a server.',
        ],
      },
      {
        heading: 'Cookies',
        body: [
          'The site sets no cookies and uses no third-party trackers. Because there are no ' +
            'analytics and no advertising, there is no cookie banner and no consent to manage.',
        ],
      },
      {
        heading: 'What stays in your browser',
        body: [
          'Your theme preference and your calculator workspace (expressions, viewport, ' +
            'settings) are stored only in your own browser\u2019s localStorage. They never leave ' +
            'your device. Clearing your browser\u2019s site data removes them permanently.',
        ],
      },
      {
        heading: 'Contact',
        body: ['If you have questions about this policy, email {email}.'],
      },
    ],
    outro: [
      'This policy will be updated if the product\u2019s data practices change. The ' +
        'last-updated date above always reflects the current version.',
    ],
  },
  terms: {
    seo: {
      title: 'Terms of Service',
      description: 'Terms of service for the Graphing Calculator: usage rules and disclaimers.',
    },
    updatedTemplate: 'Last updated: {date}',
    heading: 'Terms of Service',
    sections: [
      {
        heading: 'The service',
        body: [
          'The Graphing Calculator is provided as-is, for education and exploration. While we ' +
            'aim for correctness, we make no guarantees about the accuracy of any output, and the ' +
            'tool is not professional mathematical, engineering, or financial advice.',
        ],
      },
      {
        heading: 'Acceptable use',
        body: [
          'Use the calculator for lawful purposes only. Do not attempt to disrupt the service, ' +
            'probe it for vulnerabilities, or use it in a way that harms others.',
        ],
      },
      {
        heading: 'Changes',
        body: [
          'These terms may be updated as the product evolves; the last-updated date above ' +
            'reflects the current version. Continued use of the site after changes constitutes ' +
            'acceptance of the updated terms.',
        ],
      },
    ],
  },
  disclaimer: {
    seo: {
      title: 'Disclaimer',
      description:
        'Disclaimer for the Graphing Calculator: AI answers and numerical results are ' +
        'informational; verify important calculations independently.',
    },
    updatedTemplate: 'Last updated: {date}',
    heading: 'Disclaimer',
    sections: [
      {
        heading: 'AI assistant output is informational',
        body: [
          'The built-in AI math assistant explains concepts and interprets requests in plain ' +
            'language, but it can make mistakes — including confidently stated ones. Treat AI ' +
            'answers as a starting point, not as authoritative mathematics.',
        ],
      },
      {
        heading: 'Numerical results are computed, not proven',
        body: [
          'Roots, derivatives, integrals, limits, and other analysis results are computed ' +
            'numerically with floating-point arithmetic. They are accurate to the displayed ' +
            'precision under normal conditions, but rounding and sampling can introduce small ' +
            'errors — especially near discontinuities, sharp corners, or asymptotes. For ' +
            'homework, exams, engineering, or any decision that matters, verify important ' +
            'calculations independently.',
        ],
      },
      {
        heading: 'No professional advice',
        body: [
          'Nothing on this site constitutes professional advice of any kind — mathematical, ' +
            'educational, financial, or otherwise. The content is provided for general ' +
            'educational purposes.',
        ],
      },
      {
        heading: 'Your graphs stay yours',
        body: [
          'Graphs you save are stored only in your own browser. Shared links encode the graph ' +
            'in the link itself, so anyone with the link can open it. Do not share links ' +
            'containing anything you would not want others to see.',
        ],
      },
    ],
    outro: [
      'By using this site you accept that its authors are not liable for decisions made on ' +
        'the basis of its output. See the Terms of Service for details.',
    ],
  },
};
